[project]
name = "bastis"
authors = [
    {name = "Rafael Moret", email = "rafaelmoretgalan@gmail.com"}, 
    {name = "Cristina Espejo", email = "cristinaespejoroque@outlook.es"}
]
version = "0.1.0"
requires-python = ">=3.12"
dependencies = []

[project.optional-dependencies]
dev = ["pytest"]
